version: '2.1'

services:
  server:
    build:
      args:
        version: v0.2.5.4
      context: .
    image: ksp_dmp_server
    ports:
      - 6702:6702
      - 6703:6703
    volumes:
      - ./data/Config:/DMPServer/Config
      - ./data/Plugins:/DMPServer/Plugins
      - ./data/Universe:/DMPServer/Universe
      - ./data/logs:/DMPServer/logs
